cart/urls.py
from django.conf.urls import url

from .views import (
        cart_home, 
        cart_update,
        cart_login,
        checkout_home,
        checkout_done_view,
        cart_detail_api_view,
        )
# app_name='cart'

urlpatterns = [
    url(r'^$', cart_home, name='cart'),
    url(r'^update/$', cart_update, name='update'),
    url(r'^login/',cart_login ,name='login'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^checkout/success$', checkout_done_view, name='success'),
    url(r'^cart/api/cart/$', cart_detail_api_view, name='api-cart'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views

from django.conf.urls import url,include
from django.contrib import admin
from .views import home_page,access,logout_page,contact_page,conditions_page,policy,return_,about,get_products
from accounts.views import login_page,RegisterView,guest_register_view
from search.views import SearchProductView
from addresses.views import checkout_address_create_view
from django.views.generic import TemplateView,RedirectView


urlpatterns = [
    url(r'^$', home_page, name='index'),
    url('admin/', admin.site.urls),
    url('applogin/', login_page, name='login'),
    url('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    url('register/guest', guest_register_view, name='guest_register'),
    url('logout/', LogoutView.as_view(), name='logout'),
    url('register/', RegisterView, name='register'),
    url('contact/', contact_page, name='contact'),
    url('TAC/', conditions_page, name='TAC'),
    url('about/', about, name='about'),
    url('policy/', policy, name='policy'),
    url('return/', return_, name='returnpolicy'),
    url('accessories/', access, name='accessories'),
    url('search/',SearchProductView.as_view(), name='search'),
    url(r'^cart/', include(("cart.urls",'carts'), namespace='cart')),
    url(r'^billing/', include(("billing.urls",'billing'), namespace='billing')),
    url(r'^products/', include(("products.urls",'products'), namespace='products')),
    url(r'^orders/', include(("orders.urls",'orders'), namespace='orders')),
    # url('temp', TemplateView.as_view(template_name="socialapp/login1.html")),
    # url(r'accounts/', include('allauth.urls')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^account/', include(("accounts.urls",'account'), namespace='account')),
    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^filter/(?P<category>[\w-]+)/$', get_products, name='category'),
    
    # url(r'^password/change/done/$',
    #         auth_views.PasswordChangeDoneView.as_view(), 
    #         name='password_change_done'),
    # url(r'^password/reset/$', 
    #         auth_views.PasswordResetView.as_view(template_name = "registeration/password_reset_form.html"), 
    #         name='password_reset'),
    # url(r'^password/reset/done/$', 
    #         auth_views.PasswordResetDoneView.as_view(template_name = "registeration/password_reset_done.html"), 
    #         name='password_reset_done'),
    # url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
    #         auth_views.PasswordResetConfirmView.as_view(template_name = "registeration/password_reset_confirm.html"), 
    #         name='password_reset_confirm'),
    # url(r'^password/reset/complete/$', 
    #         auth_views.PasswordResetCompleteView.as_view(template_name = "registeration/password_reset_complete.html"), 
    #         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    #print(urlpatterns)

orders/urls.py
from django.conf.urls import url

from .views import (
        RequestRefundView,
        OrderListView, 
        OrderDetailView
        )

urlpatterns = [
    url(r'^$', OrderListView.as_view(), name='list'),
    url(r'^(?P<order_id>[0-9A-Za-z]+)/$', OrderDetailView.as_view(), name='detail'),
    url('request-refund/', RequestRefundView.as_view(), name='request-refund'),
]

cart/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed



from products.models import Product


User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)

class CartItem(models.Model):
    product     = models.ForeignKey(Product,blank=True,on_delete=models.CASCADE)
    cart        = models.ForeignKey('Cart', null=True, on_delete=models.CASCADE)
    quantity    = models.PositiveIntegerField(default=1)
    price       = models.DecimalField(decimal_places=2, max_digits=20, default=39.99)
    updated     = models.DateTimeField(auto_now_add=False ,auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        try:
            return str(self.cart.id) 
        except:
            return str(self.product.title)

class Cart(models.Model):
    user        = models.ForeignKey(User, null=True, blank=True,on_delete=models.CASCADE)
    products    = models.ManyToManyField(Product, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    isordered   = models.BooleanField(default=False)


    objects = CartManager()

    def __str__(self):
        return str(self.id)

def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)




def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.08)
    else :
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

orders/models.py
import math
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save,post_save
from billing.models import BillingProfile
from cart.models import Cart
from addresses.models import Address
from ecommerce.utils import unique_order_id_generator
from django.urls import reverse
from django.core.mail import send_mail
from django.template.loader import get_template
ORDER_STATUS_CHOICES = (
    ('created', 'Created'),
    ('paid', 'Paid'),
    ('shipped', 'Shipped'),
    ('refunded', 'Refunded'),
    ('COD','CashOnDelivery'),
)
class OrderManagerQuerySet(models.query.QuerySet):
    def by_request(self, request):
        billing_profile, created = BillingProfile.objects.new_or_get(request)
        print("love:",self.filter(billing_profile=billing_profile))
        return self.filter(billing_profile=billing_profile)
        

    def not_created(self):
        print("hate:",self.exclude(status='created'))
        return self.exclude(status='created')

class OrderManager(models.Manager):
        def get_queryset(self):
            return OrderManagerQuerySet(self.model, using=self._db)

        def by_request(self, request):
            return self.get_queryset().by_request(request)

        def new_or_get(self, billing_profile, cart_obj):
            created = False
            qs = self.get_queryset().filter(
                    billing_profile=billing_profile, 
                    cart=cart_obj, 
                    active=True,
                    status='created')
            if qs.count() == 1:
                obj = qs.first()
            else:
                obj = self.model.objects.create(
                        billing_profile=billing_profile, 
                        cart=cart_obj)
                created = True
            return obj, created





class Order(models.Model):
    billing_profile  = models.ForeignKey(BillingProfile ,null=True,blank=True,on_delete=models.CASCADE)
    order_id         = models.CharField(max_length=120, blank=True) # AB31DE3 
    shipping_address = models.ForeignKey(Address, related_name="shipping_address",null=True, blank=True,on_delete=models.CASCADE)
    # billing_address  = models.ForeignKey(Address, related_name="billing_address", null=True, blank=True,on_delete=models.CASCADE)
    address          = models.CharField(max_length=120, default="Chennai")
    cart             = models.ForeignKey(Cart,on_delete=models.CASCADE)
    status           = models.CharField(max_length=120, default='created', choices=ORDER_STATUS_CHOICES)
    shipping_total   = models.DecimalField(default=5.99, max_digits=100, decimal_places=2)
    total            = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    active           = models.BooleanField(default=True)
    updated          = models.DateTimeField(auto_now=True)
    timestamp        = models.DateTimeField(auto_now_add=True,blank=True)
    being_delivered  = models.BooleanField(default=False)
    received         = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted   = models.BooleanField(default=False)
    cash_on_delivery = models.BooleanField(default=False)

    def __str__(self):
        return self.order_id

    objects = OrderManager()  

    class Meta:
       ordering = ['-timestamp', '-updated']

    def get_absolute_url(self):
        return reverse("orders:detail", kwargs={'order_id': self.order_id})

    def get_status(self):
        if self.status == "refunded":
            return "Refunded order"
        elif self.status == "shipped":
            return "Shipped"
        return "Shipping Soon"  


    def update_total(self):
        cart_total = self.cart.total
        shipping_total = self.shipping_total
        new_total = math.fsum([cart_total, shipping_total])
        formatted_total = format(new_total, '.2f')
        self.total = formatted_total
        self.save()
        return new_total

    def check_done(self):
        billing_profile = self.billing_profile
        shipping_address = self.shipping_address
        billing_address = self.billing_address
        total   = self.total
        if billing_profile and shipping_address and billing_address and total > 0:
            return True
        return False

    def mark_paid(self):
        self.status = "paid"
        self.save()
        return self.status

def pre_save_create_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = unique_order_id_generator(instance)
    qs = Order.objects.filter(cart=instance.cart).exclude(billing_profile=instance.billing_profile)
    if qs.exists():
        qs.update(active=False)
    

pre_save.connect(pre_save_create_order_id, sender=Order)

def post_save_cart_total(sender, instance, created, *args, **kwargs):
    if not created:
        cart_obj = instance
        cart_total = cart_obj.total
        cart_id = cart_obj.id
        qs = Order.objects.filter(cart__id=cart_id)
        if qs.count() == 1:
            order_obj = qs.first()
            order_obj.update_total()

post_save.connect(post_save_cart_total, sender=Cart)


def post_save_order(sender, instance, created, *args, **kwargs):
    print("running")
    if created:
        print("Updating... first")
        instance.update_total()


post_save.connect(post_save_order, sender=Order)

class OrderConfirmQuerySet(models.query.QuerySet):
    def by_request(self, request):
        billing_profile, created = BillingProfile.objects.new_or_get(request)
        return self.filter(billing_profile=billing_profile)

class OrderConfirmationManager(models.Manager):
    def get_queryset(self):
        return OrderConfirmQuerySet(self.model, using=self._db)

class OrderConfirmation(models.Model):
    billing_profile = models.ForeignKey(BillingProfile ,null=True,blank=True,on_delete=models.CASCADE)
    order_id        = models.CharField(max_length=120, blank=True) 
    email           = models.EmailField()

    
    objects = OrderConfirmationManager()

    def __str__(self):
        return self.order_id

    def send_order_confirmation(self):
        base_url = getattr(settings, 'BASE_URL')
        # key_path = reverse("account:email-activate", kwargs={'key': self.key}) # use reverse
        # path = "{base}{path}".format(base=base_url, path=key_path)
        context = {
            # 'path': path,
            'email': self.billing_profile.email,
            'order_id': self.order_id,
          

        }
        txt_ = get_template("orders/order_confirm.txt").render(context)
        html_ = get_template("orders/order_confirm.html").render(context)
        subject = 'Order Confirmation'
        from_email = settings.DEFAULT_FROM_EMAIL
        recipient_list = [self.billing_profile.email]
        sent_mail = send_mail(
                    subject,
                    txt_,
                    from_email,
                    recipient_list,
                    html_message=html_,
                    fail_silently=False,
            )
        return sent_mail


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"

class RefundGrandQuerySet(models.query.QuerySet):
    def by_request(self, request):
        billing_profile, created = BillingProfile.objects.new_or_get(request)
        return self.filter(billing_profile=billing_profile)

class RefundGrandManager(models.Manager):
    def get_queryset(self):
        return OrderConfirmQuerySet(self.model, using=self._db)

class RefundGrandConfirmation(models.Model):
    # billing_profile = models.ForeignKey(BillingProfile ,null=True,blank=True,on_delete=models.CASCADE)
    order_id        = models.CharField(max_length=120, blank=True) 
    email           = models.EmailField()
    timestamp       = models.DateTimeField(auto_now_add=True)
    update          = models.DateTimeField(auto_now=True)

    objects = RefundGrandManager()

    def __str__(self):
        return self.order_id

    def send_refund_granted(self):
        base_url = getattr(settings, 'BASE_URL')
        # key_path = reverse("account:email-activate", kwargs={'key': self.key}) # use reverse
        # path = "{base}{path}".format(base=base_url, path=key_path)
        context = {
            # 'path': path,
            'email': self.email,
            'order_id': self.order_id
        }
        txt_ = get_template("orders/refund_req_confirm.txt").render(context)
        html_ = get_template("orders/refund_req_confirm.html").render(context)
        subject = 'Order Confirmation'
        from_email = settings.DEFAULT_FROM_EMAIL
        recipient_list = [self.email]
        sent_mail = send_mail(
                    subject,
                    txt_,
                    from_email,
                    recipient_list,
                    html_message=html_,
                    fail_silently=False,
            )
        return sent_mail

def post_save_refund_granted(sender, instance,*args, **kwargs):
    # print("Ins:",instance, instance.billing_profile, instance.billing_profile.email)
    obj = RefundGrandConfirmation.objects.create( order_id=instance, email=instance.email)
    obj.send_refund_granted()

post_save.connect(post_save_refund_granted, sender=Refund)   

orders/forms.py
from django import forms

from .models import Order

class RefundForm(forms.Form):
    order_id = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 4
    }))
    email = forms.EmailField()

orders/templates/orders/order_confirm.html
{% load static %}
<head>
    <link href="{% static 'css/bootstrap.min.css' %}" rel='stylesheet' type='text/css' />
</head>
<p>Hello,</p>

<p>Your order has been placed successfully!</p>
<p>Your Order Id: <b>{{order_id}}</b></p>
<!-- <p>Your Cart Id: <b>{{cart}}</b></p> -->
{% if order_id.status == "COD" %}
<p>Your have to pay Rs.{{order_id.total}} while delivering your product.</p>
{% endif %}




<p>Thank you, keep shopping with us!!!</p>

<p>Team Enduro<p>

orders/templates/orders/order_detail.html
{% load static %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% include "nav.html" %}
<!--/banner-->
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" type="text/css" href="{% static 'css/orders.css' %}">
<style>
	@import url(https://fonts.googleapis.com/css?family=Source+Code+Pro:400);

.word {
  bottom: 0;
  color: #fff;
  font-size: 2.5em;
  height: 2.5em;
  left: 0;
  line-height: 2.5em;
  margin: auto;
  right: 0;
  position: absolute;
  text-shadow: 0 0 10px rgba(50, 255, 50, 0.5), 0 0 5px rgba(100, 255, 100, 0.5);
  top: 0
}

.word span {
  display: inline-block;
  transform: translateX(100%) scale(0.9);
  transition: transform 500ms;
}

.word .done {
  color: #6f6;
  transform: translateX(0) scale(1);
}

.overlay {
  background-image: linear-gradient(transparent 0%, rgba(10, 16, 10, 0.5) 50%);
  background-size: 1000px 2px;
  bottom: 0;
  content: '';
  left: 0;
  position: absolute;
  right: 0;
  top: 0;
}
</style>
</head>
<body>
<div id="mainDiv" class="cart cart-table">
	<div class="container">
		<div class="cart-top">
		   <a href="index.html">home</a>
		</div>	
		<div class="cart-body">
		<div class="col-md-9 cart-items ">
			<h2>Your Orders({{object}})</h2>
	
			{% if object.cart.cartitem_set.exists %}
				
		   {% for item in object.cart.cartitem_set.all %}
		   		<div class="cart-header">
				<div class="cart-sec">
					   <div class="cart-item cyc">
							<img src="{{ item.product.image.url }}"/>
					   </div>
					  
					  <div class="cart-item-info">
							<h4>{{ item.product.title }}</h4><br/>
							<h4>₹. {{ item.product.price }}</h4>
                            <h4><span class="quantity">Quantity: {{ item.quantity }}</span></h4>
					
					  </div>
					<div class="delivery">
			
							<span>Delivered in 2-3 bussiness days</span>
							
							<div class="clearfix"></div>
				 </div>
				 </div>
				</div>
			{% endfor %}
		   
			{% endif %}
			
		
            
				   
		</div>
		<div class="col-md-3 cart-total">
			<h7 class="continue1">Order Total</h7>
			<div class="price-details">
				<b><span>SubTotal : </span></b>
				<span class="cart-subtotal">{{ object.cart.total }}</span><br/>
				<b><span>ShippingTotal : </span></b>
				<span class="cart-subtotal">{{ object.shipping_total }}</span><br/>
				<b><span>Order Total : </span></b>
				<span class="cart-subtotal">{{ object.total }}</span><br/>
				<b><span>Order Status : </span></b>
				<span class="cart-subtotal">{{ object.get_status }}</span><br/>			 
			</div>	
			
			<div class="clearfix"></div>
			<a class="order1" href="{% url 'orders:request-refund' %}" onclick="Login();">Cancel Order</a>
		
		   </div>
	
		
	</div>
		
</div>

</body>
</html>

orders/templates/orders/order_list.html
{% load static %}
{% include "nav.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" type="text/css" href="{% static 'css/orders.css' %}">
</head>
<body>
<div class='row'>
    <!-- <div class='center'> -->
       <center> <h1>Orders</h1></center><br>
    <!-- </div> -->
</div>
<div class="container1">
<div class='row'>
    <div class='col'>
        <table class='table'>
            <thead><th>Order Id(#)</th><th>Status</th><th>Total</th></thead>

            <tbody>
                {% for object in object_list %}
                    <tr>
                        <td><a href='{{ object.get_absolute_url }}' class="anchor";>{{ object.order_id }}</a></td>
                        <td style="color: #009900;">{{ object.get_status }}</td>
                        <td style="color: #b12704;"><b>₹.{{ object.total }}</b></td>
                    </tr>
                {% empty %}
                <tr><td colspan="3"><p class='lead'>No orders yet.</td></tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
</div>
</div>
{% include "footer1.html" %}

</body>
</html>

orders/templates/orders/refund_req_confirm.html
<p>Hello,</p>

<p>Your request for product {{order_id}} refund has been successfully received. After reviewing the products will update the status of ur refund
</p>



<p>Thank you, keep shopping with us!!!</p>

<p>Team Enduro</p>

orders/templates/orders/request_refund.html
{% load static %}

{% include "nav.html" %}
<!-- <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"> -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="{% static 'css/password-reset.css' %}" rel='stylesheet' type='text/css' />

<div class="form-gap"></div>
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="text-center">
                    <h2>Request Refund</h2><br/>
<!-- <div class="container"> -->
    {% for message in messages %}
    <div class="alert alert-danger">
      {{message}}
    </div>
    {% endfor %}
    
    <!-- <form method="POST"> -->
        <!-- {% csrf_token %} -->
        <form method="POST" id="refundForm" >{% csrf_token %}
		 
          <div class="form-group">
            <div class="col-6-sm-12">
              <!-- <label for="id_order_id">Order id:</label> -->
              <input type="text" name="order_id" required id="id_order_id" class="form-control" placeholder="Enter your OrderId">
            </div>
          </div>
        
          <div class="form-group">
            <div class="col-6-sm-12">
              <!-- <label for="id_email">Email:</label> -->
              <input type="email" name="email" required id="id_email" class="form-control" placeholder="Enter your Email">
            </div>
          </div>
          <!-- <label for="id_message">Message:</label> -->
          <textarea name="message" cols="40" rows="4" required id="id_message" class="form-control" placeholder="Share your Query"></textarea>
         <br/>
          
          <button type='submit' class='btn btn-primary'>Submit</button> 
          
        
          
          </form>
          <!-- {{form.as_p}} -->
        <!-- <button type='submit' class='btn btn-primary'>Submit</button> -->
    <!-- </form> -->

    </div>
    </div>
    </div>
    </div>
    </div>
    </div>