cart/urls.py
from django.conf.urls import url

from .views import (
        cart_home, 
        cart_update,
        cart_login,
        checkout_home,
        checkout_done_view,
        cart_detail_api_view,
        )
# app_name='cart'

urlpatterns = [
    url(r'^$', cart_home, name='cart'),
    url(r'^update/$', cart_update, name='update'),
    url(r'^login/',cart_login ,name='login'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^checkout/success$', checkout_done_view, name='success'),
    url(r'^cart/api/cart/$', cart_detail_api_view, name='api-cart'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views

from django.conf.urls import url,include
from django.contrib import admin
from .views import home_page,access,logout_page,contact_page,conditions_page,policy,return_,about,get_products
from accounts.views import login_page,RegisterView,guest_register_view
from search.views import SearchProductView
from addresses.views import checkout_address_create_view
from django.views.generic import TemplateView,RedirectView


urlpatterns = [
    url(r'^$', home_page, name='index'),
    url('admin/', admin.site.urls),
    url('applogin/', login_page, name='login'),
    url('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    url('register/guest', guest_register_view, name='guest_register'),
    url('logout/', LogoutView.as_view(), name='logout'),
    url('register/', RegisterView, name='register'),
    url('contact/', contact_page, name='contact'),
    url('TAC/', conditions_page, name='TAC'),
    url('about/', about, name='about'),
    url('policy/', policy, name='policy'),
    url('return/', return_, name='returnpolicy'),
    url('accessories/', access, name='accessories'),
    url('search/',SearchProductView.as_view(), name='search'),
    url(r'^cart/', include(("cart.urls",'carts'), namespace='cart')),
    url(r'^billing/', include(("billing.urls",'billing'), namespace='billing')),
    url(r'^products/', include(("products.urls",'products'), namespace='products')),
    url(r'^orders/', include(("orders.urls",'orders'), namespace='orders')),
    # url('temp', TemplateView.as_view(template_name="socialapp/login1.html")),
    # url(r'accounts/', include('allauth.urls')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^account/', include(("accounts.urls",'account'), namespace='account')),
    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^filter/(?P<category>[\w-]+)/$', get_products, name='category'),
    
    # url(r'^password/change/done/$',
    #         auth_views.PasswordChangeDoneView.as_view(), 
    #         name='password_change_done'),
    # url(r'^password/reset/$', 
    #         auth_views.PasswordResetView.as_view(template_name = "registeration/password_reset_form.html"), 
    #         name='password_reset'),
    # url(r'^password/reset/done/$', 
    #         auth_views.PasswordResetDoneView.as_view(template_name = "registeration/password_reset_done.html"), 
    #         name='password_reset_done'),
    # url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
    #         auth_views.PasswordResetConfirmView.as_view(template_name = "registeration/password_reset_confirm.html"), 
    #         name='password_reset_confirm'),
    # url(r'^password/reset/complete/$', 
    #         auth_views.PasswordResetCompleteView.as_view(template_name = "registeration/password_reset_complete.html"), 
    #         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    #print(urlpatterns)

cart/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed



from products.models import Product


User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)

class CartItem(models.Model):
    product     = models.ForeignKey(Product,blank=True,on_delete=models.CASCADE)
    cart        = models.ForeignKey('Cart', null=True, on_delete=models.CASCADE)
    quantity    = models.PositiveIntegerField(default=1)
    price       = models.DecimalField(decimal_places=2, max_digits=20, default=39.99)
    updated     = models.DateTimeField(auto_now_add=False ,auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        try:
            return str(self.cart.id) 
        except:
            return str(self.product.title)

class Cart(models.Model):
    user        = models.ForeignKey(User, null=True, blank=True,on_delete=models.CASCADE)
    products    = models.ManyToManyField(Product, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    isordered   = models.BooleanField(default=False)


    objects = CartManager()

    def __str__(self):
        return str(self.id)

def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)




def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.08)
    else :
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

cart/views.py
from django.http import JsonResponse,HttpResponse
from django.contrib.auth import authenticate, login, get_user_model
from django.shortcuts import render,redirect
from django.utils.http import is_safe_url
from django.views.decorators.csrf import csrf_exempt
from decimal import Decimal
from billing.models import BillingProfile
from accounts.models import GuestEmail,User
from accounts.forms import LoginForm,GuestForm
from addresses.forms import AddressForm
from orders.models import Order
from .models import Cart,CartItem
from products.models import Product
from addresses.models import Address
from accounts.signals import user_logged_in


c = 0
import razorpay
client = razorpay.Client(auth=("rzp_test_fu6uylByoiLTWv", "UHCkK8GTEqFliNdSub9L3Vrd"))

def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [{"id": x.id, "name": x.name, "price": x.price, "image": x.image.url} for x in cart_obj.products.all()] # [<object>, <object>, <object>]
    # products_list = []
    # for x in cart_obj.products.all():
    #     products_list.append(
    #             {"name": x.name, "price": x.price}
    #         )
    cart_data  = {"products": products, "subtotal": cart_obj.subtotal, "total": cart_obj.total}
    print(cart_data)
    return JsonResponse(cart_data)



def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    if cart_obj.isordered:
        print("*****")
        request.session['cart_items'] = 0
        del request.session['cart_id']
		
    return render(request, "carts/cart.html", {"cart": cart_obj})

def cart_update(request):
    product_id = request.POST.get('product_id')
    # print(product_id)
    try:
        qty = request.POST.get('qty')
        update_qty = True
    except:
        qty = None
        update_qty = False

    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("Show message to user, product is gone?")
            return redirect("cart:cart")

        cart_obj, new_obj = Cart.objects.new_or_get(request)
        request.session['cart_id'] = cart_obj.id
        print("CCCart:",request.session['cart_id'],cart_obj)
        # cart_item, created = CartItem.objects.get_or_create(cart=cart_obj, product=product_obj)
        # if created:
        #     print("created")
  

        # print("Product",product_obj,cart_obj.cartitem_set.all())
        products = [ x.product.name for x in cart_obj.cartitem_set.all()] # [<object>, <object>, <object>]
        print("Prod Obj",product_obj)

        print("Prod Id",products)
        if str(product_obj) in products:
            cart_item = CartItem.objects.get(cart=cart_obj, product=product_obj)
            cart_item.delete()
            print("sss",product_obj)
            cart_obj.products.remove(product_obj)
            
            added = False
        else:
            cart_item, created = CartItem.objects.get_or_create(cart=cart_obj, product=product_obj)
            cart_obj.products.add(product_obj)
            # cart_item.add(product_obj)
            print("elseeee") 
            added = True
        
        if update_qty and qty:
            if int(qty) == 0:
                cart_item.delete()
            else:
                cart_item.quantity = qty
                cart_item.save()
        else: 
            pass
        new_total = 0.0
        for x in cart_obj.cartitem_set.all():
            line_item = float(x.product.price) * x.quantity
            cart_item.price= line_item
            new_total += line_item

        request.session['cart_items'] = cart_obj.cartitem_set.count()
        print("cartTotal:",cart_obj.cartitem_set.count())
        cart_obj.subtotal = new_total
        if cart_obj.subtotal > 0:
            cart_obj.total = Decimal(cart_obj.subtotal) 
            print("cart_total:",cart_obj.total)
        else :
            cart_obj.total = 0.00
        cart_obj.save()
        # return redirect(product_obj.get_absolute_url())
        print("---------------",request.is_ajax())
        if request.is_ajax(): # Asynchronous JavaScript And XML / JSON
            print("Ajax request")
            json_data = {
                "added": added,
                "removed": not added,
                "cartItemCount": cart_obj.cartitem_set.count()
            }
            return JsonResponse(json_data)
    return redirect("cart:cart")



def checkout_home(request):
    global c
    c+=1
    order_status = None
    print(c)
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.cartitem_set.count()== 0:
        return redirect("cart:cart")

    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)
    print("CHeck:",shipping_address_id)

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    if billing_profile is not None:
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
  
    if shipping_address_id:
        order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
        print("CHeck:",shipping_address_id)
        order_obj.save()
        return redirect("billing:razor")
        # order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
        # print("CHeck:",shipping_address_id)
        # order_obj.save()
        # shipping_address=order_obj.shipping_address.get_address
        # order_amount = int(100 * cart_obj.total)
        # order_currency = 'INR'
        # order_receipt = 'order_rcptid_11'
        # response = client.order.create(dict(amount=order_amount, currency=order_currency, receipt=order_receipt, payment_capture='0'))
        # order = response['id']
        # order_status = response['status']
        # print("order razor:",order, order_status)
        # print("Order amt:",order_amount )
		# # print( order_obj.billing_profile.get_address)
        # if order_status=='created':
        #     context={
        #     "Order_total":order_amount,
        #     "Billing_address":billing_profile,
        #     "object": order_obj,
        #     "order_id":order,
        #     "cart": cart_obj,
        #     "shipping_address":shipping_address
            
        #     }
        #     return render(request, 'billing/confirm_order.html', context)
    
    context = {
            "cart_obj" : cart_obj,
            "object": order_obj,
            "billing_profile": billing_profile,
            "login_form": login_form,
            "guest_form": guest_form,
            "address_form":address_form
        }
    
    
     
    return render(request, "carts/checkout.html", context)
def checkout_done_view(request):
    return render(request, "carts/checkout-done.html", {})

def cart_login(request):
    if request.method =='POST':
        username = request.POST['username']
        password = request.POST['password']
        next_ = request.GET.get('next')
        next_post = request.POST.get('next')
        redirect_path = next_ or next_post or None
        user = authenticate(request, username=username, password=password)
        print(user)
        if user is not None:
            login(request, user)
            user_logged_in.send(user.__class__, instance=user, request=request)
            try:
                del request.session['guest_email_id']
            except:
                pass
            if is_safe_url(redirect_path, request.get_host()):
                return redirect(redirect_path)
            else:
                return redirect("cart:checkout")
        else:
            print("Error")
        
    return render(request, "accounts/index.html")


# @csrf_exempt
# def handlerequest(request):
#     return HttpResponse('done')
#     pass

cart/templates/carts/cart.html
{% load static %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% include "nav.html" %}

<!--/banner-->
<div class="cart cart-table">
	<div class="container-fluid">
		<div class="cart-top">
		   <a href="index.html">home</a>
		</div>	
		<div class="cart-body">
		<div class="col-md-9 cart-items ">
			<h2>My Shopping Bag </h2>
				<!-- ({{ request.session.cart_items }})</h2> -->
			   <!-- <script>$(document).ready(function(c) {
				   $('.close1').on('click', function(c){
					   $('.cart-header').fadeOut('slow', function(c){
						   $('.cart-header').remove();
					   });
					   });	  
				   });
			  </script> -->
			  {% if cart.cartitem_set.exists and not cart.isordered %}
		   <!--    <div clas="cart-products"> -->
				<div class="cart-header">
					{% for item in cart.cartitem_set.all %}
			<!-- <div class="cart-header"> -->
				<!-- <div class="close1"> </div> -->
				<div class="cart-sec">
					   <div class="cart-item cyc">
							<img src="{{ item.product.image.url }}"/>
					   </div>
					  <div class="cart-item-info">
							<h4>{{ item.product.title }}</h4><br/>
							<h4>₹.{{ item.product.price }}</h4>
							<h4><span>Quantity: {{ item.quantity }}</span></h4>
							<!-- <p class="qty">Qty ::</p>
							<input min="1" type="number" id="quantity" name="quantity" value="1" class="form-control input-small"> -->
							{% include 'carts/snippets/remove-product.html' with product_id=item.product.id %}
					  </div>
					  <!-- <div class="clearfix"></div> -->
					   <div class="delivery">
							<!-- <p>Service Charges:: Rs.100.00</p> -->
								<span>Delivered in 5-7 bussiness days</span>
							<div class="clearfix"></div>
					   </div>						
				 </div>
				 <div class="cart-item-remove-form" style='display:none'>
				   {% include 'carts/snippets/remove-product.html' %}
					</div>
		   <!--  </div> -->
			{% endfor %}
		   </div>
			{% endif %}
			<!-- <script>$(document).ready(function(c) {
				   $('.close2').on('click', function(c){
						   $('.cart-header2').fadeOut('slow', function(c){
					   $('.cart-header2').remove();
				   });
				   });	  
				   });
			</script> -->
				   
		</div>
		
		
		<div class="col-md-3 cart-total">
			<a class="continue" href="{% url 'products:products' %}">Continue to basket</a>
			<div class="price-details">
				<h3>Price Details</h3>
				<span>Total</span>
				<span class="cart-subtotal">{% if not cart.isordered %}{{ cart.subtotal }} {% else %} {{0.0}} {% endif %}</span>
				<span>Discount</span>
				<span class="total">---</span>
				<!-- <span>Delivery Charges</span>
				<span class="total">100.00</span> -->
				<div class="clearfix"></div>				 
			</div>	
			<h4 class="last-price">TOTAL</h4>
			<span class="total final">{% if not cart.isordered %}{{ cart.subtotal }} {% else %} {{0.0}} {% endif %}</span>
			<div class="clearfix"></div>
			<a class="order" href="{% if request.user.is_authenticated %}{% url 'cart:checkout' %}{% else %}{% url 'cart:login' %}{% endif %}">Place Order</a>
		
		   </div>
	</div>
   
   </div>
</div>
{% include "footer.html" %}

cart/templates/carts/checkout-done.html
{% load static %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% include "nav.html" %}

<!--/banner-->
<!-- <div class="parts">
	 <div class="container">
        <h2>CHECKOUT</h2>
        <div class="bike-parts-sec">
            <div class="bike-parts">
               <div class="top">
                   <ul>
                       <li><a href="index.html">home</a></li>
                       <li><a href="#"> / </a></li>
                       <li><a href="#">checkout</a></li>
                   </ul>				 
				</div>
				{{object.order_id}} --- {{object.cart}}

				{% if not billing_profile %}
				<div class='row text-center'>
					<div class='col-12 col-md-6'>
						<p class='lead'>Login</p> 
						{% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
					</div>
					<div class='col-12 col-md-6'>
						{% url "guest_register" as guest_register_url %}
						{% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
						
					</div>
				</div>
					
				{% else %}
				{% if not object.shipping_address %}

				<div class='row'>
				   <div class='col-md-6 mx-auto col-10'>
					   <p class='lead'>Shipping Address</p>
					   <hr/>
				   {% url "checkout_address_create" as checkout_address_create %}
				   {% include 'addresses/forms.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}
				</div>
			   </div>
	   
	   
			   {% elif not object.billing_address %}
			   <div class='row'>
				   <div class='col-md-6 mx-auto col-10'>
					   <p class='lead'>Billing Address</p>
					   <hr/>
				   {% url "checkout_address_create" as checkout_address_create %}
				   {% include 'addresses/forms.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}
				</div>
			   </div>
			   {% else %}
					   <h1>Final checkout</h1>
					   <p>Cart Items: {% for product in object.cart.products.all %}{{ product }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
					   <p>Shipping Address: {{ object.shipping_address.get_address }}</p>
					   <p>Billing Address: {{ object.shipping_address.get_address }}</p>
						<p> Cart Total: {{object.cart.total}}</p>
						<p>Shipping total :{{object.shipping_total}}</p>
						<p>Order Total : {{object.total}}</p>
						<form class='form' method='POST' action="">{% csrf_token %}
							<button type='submit' class="btn btn-success">Checkout</button>
						</form>
				{% endif %}
			{% endif %} -->
		 <!-- <div class="col-md-9 cart-items"> -->
			 <!-- <h2>My Shopping Bag (2)</h2>
			     <script>$(document).ready(function(c) {
					$('.close1').on('click', function(c){
						$('.cart-header').fadeOut('slow', function(c){
							$('.cart-header').remove();
						});
						});	  
					});
			   </script> -->
			   <!-- {% if cart.products.exists %}
			{% for product in cart.products.all %}
			 <div class="cart-header">
				 <div class="close1"> </div>
				 <div class="cart-sec">
						<div class="cart-item cyc">
							 <img src="{{ product.image.url }}"/>
						</div>
					   <div class="cart-item-info">
							 <h3>{{ product.title }}<span>Model No: 3578</span></h3>
							 <h4><span>Rs.</span>{{ product.price }}</h4>
							 <p class="qty">Qty ::</p>
							 <input min="1" type="number" id="quantity" name="quantity" value="1" class="form-control input-small">
							 {% include 'products/snippets/update-cart.html' with product=product cart=cart in_cart=True %}
					   </div>
					   <div class="clearfix"></div>
						<div class="delivery">
							 <p>Service Charges:: Rs.100.00</p>
							 <span>Delivered in 2-3 bussiness days</span>
							 <div class="clearfix"></div>
				        </div>						
				  </div>
			 </div>
			 {% endfor %}
		 	{% endif %}
			  <script>$(document).ready(function(c) {
					$('.close2').on('click', function(c){
							$('.cart-header2').fadeOut('slow', function(c){
						$('.cart-header2').remove();
					});
					});	  
					});
			 </script> -->
					
		 <!-- </div> -->
		 
		 
		 <!-- <div class="col-md-3 cart-total">
			 <a class="continue" href="{% url 'products:products' %}">Continue to basket</a>
			 <div class="price-details">
				 <h3>Price Details</h3>
				 <span>Total</span>
				 <span class="total">{{ cart.subtotal }}</span>
				 <span>Discount</span>
				 <span class="total">---</span>
				 <span>Delivery Charges</span>
				 <span class="total">150.00</span>
				 <div class="clearfix"></div>				 
			 </div>	
			 <h4 class="last-price">TOTAL</h4>
			 <span class="total final">{{ cart.total }}</span>
			 <div class="clearfix"></div>
			 <a class="order" href="#">Place Order</a>
			 <div class="total-item">
				 <h3>OPTIONS</h3>
				 <h4>COUPONS</h4>
				 <a class="cpns" href="#">Apply Coupons</a>
				 <p><a href="{% url 'login' %}">Log In</a> to use accounts - linked coupons</p>
			 </div>
			</div> -->
	 <!-- </div>
</div>
</div>
</div> -->
<!---->
<head>
    <title>Cart Report</title>
</head>
<body>
    <!-- {{response}} -->
   <center><h2>Payment status regarding your Order Id: {{response.ORDERID}}</h2></center><hr/>
    {% if response.RESPCODE == '01' %}
    <div class='col-6 mx-auto py-5 text-center'>
		<h1 class='display-1'>Thank you for your order!!!</h1>
		  </div>
    {% else %}
    <div class='col-6 mx-auto py-5 text-center'>
		<h1 class='display-1'>Ouch your order failed!!!</h1>
		  </div> 
	{% endif %}


	
</body>

  

cart/templates/carts/checkout.html
{% load static %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% include "nav.html" %}
<!--/banner-->
<html>
<div class="parts">
	 <div class="container">
    

				{% if not billing_profile %}
				<div class='row text-center'>
					<div class='col-12 col-md-6'>
						<p class='lead'>Login</p> 
						{% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
					</div>
					<div class='col-12 col-md-6'>
						{% url "guest_register" as guest_register_url %}
						{% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
						
					</div>
				</div>
					
				{% else %}
			
				  <h2 class="text-center">Shipping address</h2>
				  <hr class="mb-4">
				<!-- <div class='row'>
				   <div class='col-md-6 mx-auto col-10'> -->
				   {% url "checkout_address_create" as checkout_address_create %}
				   {% include 'addresses/forms.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}
				<!-- </div>
			   </div> -->
			   
	
	   
			  
				<!-- </div>
			   </div> -->
			  
			{% endif %}
		 
	 <!-- </div> -->
<!-- </div> -->
</div>
</div> 
<!---->
{% include "footer.html" %}
</html>