cart/urls.py
from django.conf.urls import url

from .views import (
        cart_home, 
        cart_update,
        cart_login,
        checkout_home,
        checkout_done_view,
        cart_detail_api_view,
        )
# app_name='cart'

urlpatterns = [
    url(r'^$', cart_home, name='cart'),
    url(r'^update/$', cart_update, name='update'),
    url(r'^login/',cart_login ,name='login'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^checkout/success$', checkout_done_view, name='success'),
    url(r'^cart/api/cart/$', cart_detail_api_view, name='api-cart'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views

from django.conf.urls import url,include
from django.contrib import admin
from .views import home_page,access,logout_page,contact_page,conditions_page,policy,return_,about,get_products
from accounts.views import login_page,RegisterView,guest_register_view
from search.views import SearchProductView
from addresses.views import checkout_address_create_view
from django.views.generic import TemplateView,RedirectView


urlpatterns = [
    url(r'^$', home_page, name='index'),
    url('admin/', admin.site.urls),
    url('applogin/', login_page, name='login'),
    url('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    url('register/guest', guest_register_view, name='guest_register'),
    url('logout/', LogoutView.as_view(), name='logout'),
    url('register/', RegisterView, name='register'),
    url('contact/', contact_page, name='contact'),
    url('TAC/', conditions_page, name='TAC'),
    url('about/', about, name='about'),
    url('policy/', policy, name='policy'),
    url('return/', return_, name='returnpolicy'),
    url('accessories/', access, name='accessories'),
    url('search/',SearchProductView.as_view(), name='search'),
    url(r'^cart/', include(("cart.urls",'carts'), namespace='cart')),
    url(r'^billing/', include(("billing.urls",'billing'), namespace='billing')),
    url(r'^products/', include(("products.urls",'products'), namespace='products')),
    url(r'^orders/', include(("orders.urls",'orders'), namespace='orders')),
    # url('temp', TemplateView.as_view(template_name="socialapp/login1.html")),
    # url(r'accounts/', include('allauth.urls')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^account/', include(("accounts.urls",'account'), namespace='account')),
    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^filter/(?P<category>[\w-]+)/$', get_products, name='category'),
    
    # url(r'^password/change/done/$',
    #         auth_views.PasswordChangeDoneView.as_view(), 
    #         name='password_change_done'),
    # url(r'^password/reset/$', 
    #         auth_views.PasswordResetView.as_view(template_name = "registeration/password_reset_form.html"), 
    #         name='password_reset'),
    # url(r'^password/reset/done/$', 
    #         auth_views.PasswordResetDoneView.as_view(template_name = "registeration/password_reset_done.html"), 
    #         name='password_reset_done'),
    # url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
    #         auth_views.PasswordResetConfirmView.as_view(template_name = "registeration/password_reset_confirm.html"), 
    #         name='password_reset_confirm'),
    # url(r'^password/reset/complete/$', 
    #         auth_views.PasswordResetCompleteView.as_view(template_name = "registeration/password_reset_complete.html"), 
    #         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    #print(urlpatterns)

templates/temp/TAC.html
{% include "nav.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container">
    <center><p><b>TERMS OF SERVICE</b></center>

        <br><br>
        
       
        
        <!-- Terms and condition  -->
        <img  src="{% static 'images/p10.jpg' %}" alt="hello" />

<b>SECTION-1 INTRODUCTION</b><br> 
  By using this website you agreed to accept all terms and condition written in here . you must not use this website if you disagree with any of these website standard terms and conditions .<br> 

<b>SECTION-2 INTELLECTUAL PROPERTY RIGHTS</b><br>
Other than the content you own, under these Terms, MM ENDURO and/or its licensors own all the intellectual property rights and materials contained in this Website.
You are granted limited license only for purposes of viewing the material contained on this Website.<br>

<b>SECTION-3 RESTRICTIONS</b><br>
You are specifically restricted from all of the following:<br>
<ul>
<li>Publishing any Website material in any other media;</li>
<li>Selling, sublicensing and/or otherwise commercializing any Website material;</li>
<li>Publicly performing and/or showing any Website material;</li>
<li>Using this Website in any way that is or may be damaging to this Website;</li>
<li>Using this Website in any way that impacts user access to this Website;</li>
<li>Using this Website contrary to applicable laws and regulations, or in any way may cause harm to the Website, or to any person or business entity;
engaging in any data mining, data harvesting, data extracting or any other similar activity in relation to this Website;</li>
<li>Using this Website to engage in any advertising or marketing.</li>
</ul>
<b>SECTION-4 NO WARRANTIES</b><br>
This Website is provided "as is," with all faults, and MM ENDURO express no representations or warranties, of any kind related to this Website or the materials contained on this Website. Also, nothing contained on this Website shall be interpreted as advising you.<br>
<b>SECTION-5 VARIATION OF TERMS</b><br>
MM ENDURO is permitted to revise these Terms at any time as it sees fit, and by using this Website you are expected to review these Terms on a regular basis.<br>
<b>SECTION-6 LIMITATION OF LIABILITY</b><br>
In no event shall MM ENDURO, nor any of its officers, directors and employees, shall be held liable for anything arising out of or in any way connected with your use of this Website whether such liability is under contract.  MM ENDURO, including its officers, directors and employees shall not be held liable for any indirect, consequential or special liability arising out of or in any way related to your use of this Website.<br>
<b>SECTION-7 INDEMNIFICATION</b><br>
You hereby indemnify to the fullest extent MM ENDURO from and against any and/or all liabilities, costs, demands, causes of action, damages and expenses arising in any way related to your breach of any of the provisions of these Terms.<br>
<b>SECTION-8 SEVERABILITY</b><br>
If any provision of these Terms is found to be invalid under any applicable law, such provisions shall be deleted without affecting the remaining provisions herein.<br>
<b>SECTION-9 ASSIGNMENT</b><br>
The MM ENDURO is allowed to assign, transfer, and subcontract its rights and/or obligations under these Terms without any notification. However, you are not allowed to assign, transfer, or subcontract any of your rights and/or obligations under these Terms.<br>
<b>SECTION-10 ENTIRE AGREEMENT</b><br>
These Terms constitute the entire agreement between MM ENDURO and you in relation to your use of this Website, and supersede all prior agreements and understandings.<br>
<b>SECTION-11 GOVERNING LAW & JURISDICTION</b><br>
These Terms will be governed by and interpreted in accordance with the laws of the State of in, and you submit to the non-exclusive jurisdiction of the state and federal courts located in in for the resolution of any disputes.<br>
<b>SECTION-12 CONTACT INFORMATION</b><br>
Questions about the Terms of Service should be sent to us at mmenduro122@gmail.com.<br><br><BR><BR></p>
    </div>
    {% include "footer.html" %}
</body>
</html>

templates/temp/about.html
{% load static %}

{% include "nav.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <p><br><br>
           <center><b> ABOUT US</b><br><br></center>
           <!-- <h1>Return and Refund Policy</h1> -->
           <ul>
   <p> <li>Welcome to MMENDURO, your number one source for all kinds of automobile parts.</p></li> <br>
   <p><li>We're dedicated to giving you the very best of [product], with a focus on [store characteristic 1], [store characteristic 2], [store characteristic 3].</p></li><br>


<p><li>Founded in 2020 by Thanigaivel S, MMENDURO has come a long way from its beginnings in Velacherry.</li></p><br>
     <p><li>When Thanigaivel first started out, his passion for "automotive-parts" drove them to  quit day job  so that MMENDURO can offer you competitive differentiator  "the world's most advanced automobile".</li></p><br>
 <p><li>We now serve customers all over country, and are thrilled that we're able to turn our passion into my own website.</li></p><br>


<p><li>I hope you enjoy our products as much as we enjoy offering them to you.</li></p><br>
<p><li>     If you have any questions or comments, please don't hesitate to contact me.</li></p><br>
</ul>


<p>Sincerely,</p><br>

     Thanigaivel S
</div>

{% include "footer.html" %}
        
</body>
</html>

templates/temp/contact.html
{% load static %} 
 {% include "nav.html" %}
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script> -->
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css"
/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
<link href="{% static 'css/contact.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'ecomjs/ecomm.js' %}" rel="stylesheet" />
<div class="container-fluid">
<div id="contact">
  <h1 class="section-header">Help Center</h1>
  <div class="desc">We are here to help you</div><hr/>

  <div class="contact-wrapper">
    <!---------------- 
  
		CONTACT PAGE LEFT 
	  
		----------------->

    <form
      class="form-horizontal"
      role="form"
      method="post"
      action="{% url 'contact' %}"
    >
      {% csrf_token %} {% for message in messages %}
      <div class="alert alert-primary">
        {{message}}
      </div>
      {% endfor %}

      <div class="form-group">
        <div class="col-sm-12">
          <input
            type="text"
            class="form-control"
            id="name"
            placeholder="NAME"
            name="name"
            required
            value=""
          />
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-12">
          <input
            type="email"
            class="form-control"
            id="email"
            placeholder="EMAIL"
            name="email"
            required
            value=""
          />
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-12">
          <input
            type="text"
            class="form-control"
            id="order_id"
            placeholder="ORDER ID"
            name="order_id"
            value=""
          />
        </div>
      </div>

      <textarea
        class="form-control"
        rows="10"
        id="content"
        required
        placeholder="MESSAGE"
        name="message"
      ></textarea>

      <button
        class="btn btn-primary send-button"
        id="submit"
        type="submit"
        value="SEND"
      >
        <div class="button">
          <i class="fa fa-paper-plane"></i><span class="send-text">SEND</span>
        </div>
      </button>
    </form>

    <!---------------- 
  
		CONTACT PAGE RIGHT 
	  
		----------------->

     <div class="direct-contact-container"> 
      <ul class="contact-list">
        <li class="list-item">
          <i class="fa fa-map-marker fa-2x"
            ><span class="contact-text place"
              >Velachery | Chennai
            </span></i
          >
        </li> 

        <!-- <li class="list-item">
          <i class="fa fa-phone fa-2x"
            ><span class="contact-text phone"
              ><a href="tel:1-212-555-5555" title="Give me a call"
                >9600303564</a
              ></span
            ></i
          >
        </li> -->

        <li class="list-item">
          <i class="fa fa-envelope fa-2x"
            ><span class="contact-text gmail"
              ><a href="mailto:#" title="Send me an email"
                >mmenduro122@gmail.com</a>
              </span
            ></i
          >
        </li>
      </ul>

      <hr />
      <ul class="social-media-list">
        <!-- <a href="https://www.youtube.com/">Continue to basket</a> -->
        <li>
          <a href="https://www.gmail.com/" class="contact-icon">
            <i class="fa fa-google" aria-hidden="true"></i
          ></a>
        </li>
        <!-- <li>
          <a
            href="https://twitter.com/login"
            target="_blank"
            class="contact-icon"
          >
            <i class="fa fa-twitter" for="fa-twitter" aria-hidden="true"></i
          ></a>
        </li> -->
        <li>
          <a
            href="https://instagram.com/mm_enduro_?igshid=kl8istfiisls"
            target="_blank"
            class="contact-icon"
          >
            <i class="fa fa-instagram" aria-hidden="true"></i
          ></a>
        </li>
        <li>
          <a
            href="https://www.facebook.com/"
            target="_blank"
            class="contact-icon"
          >
            <i class="fa fa-facebook" aria-hidden="true"></i
          ></a>
        </li>
      </ul>
      <hr />

      <div class="copyright">&copy; ALL OF THE RIGHTS RESERVED</div>
    </div>
  </div>
</div>
</div>
{% include "footer.html" %}

templates/temp/demo.html
<!--doctype html-->
<html>
<head>
<meta charset="utf-8">
<title>Product-slider</title>
<!--Adding Links  -->
<link  rel="stylesheet" href="{% static 'css/swiper.min.css' %}"/>
<link rel="stylesheet" href="{% static 'css/style1.css' %}"/>

</head>
<body>
<!--slider 1 bags------------------------------------------>
<div class="heading">
<h1>F E A T U R E D &emsp; P R O D U C T S</h1>
</div>
<!--swiper slider-->
<div class="swiper-container">
    <div class="swiper-wrapper">
    <!--slide 1-------------------------------------->
      <div class="swiper-slide">
      <div class="slider-box">
<p class="time">New</p>
<div class="img-box">
<img src="{% static 'images/car.jpg' %}">
</div>
<p class="detail">Black ladies bags collections
<a href="#" class="price">Price-40$</a>
</p>
<div class="cart">
<a href="#">Add To Cart</a>
</div>
</div>
      
      </div>
      
      
      
      <!--slide 2-------------------------------------->
      <div class="swiper-slide">
      <div class="slider-box">
<p class="time">New</p>
<div class="img-box">
<img src="{% static 'images/car.jpg' %}">
</div>
<p class="detail">Black ladies bags collections
<a href="#" class="price">Price-40$</a>
</p>
<div class="cart">
<a href="#">Add To Cart</a>
</div>
</div>
      
      </div>
      
      
      
      
      <!--slide 3-------------------------------------->
      <div class="swiper-slide">
      <div class="slider-box">
<p class="time">New</p>
<div class="img-box">
<img src="{% static 'images/car.jpg' %}">
</div>
<p class="detail">Black ladies bags collections
<a href="#" class="price">Price-40$</a>
</p>
<div class="cart">
<a href="#">Add To Cart</a>
</div>
</div>
      
      </div>
      
      
      
      
      <!--slide 4-------------------------------------->
      <div class="swiper-slide">
      <div class="slider-box">
<p class="time">New</p>
<div class="img-box">
<img src="{% static 'images/car.jpg' %}">
</div>
<p class="detail">Black ladies bags collections
<a href="#" class="price">Price-40$</a>
</p>
<div class="cart">
<a href="#">Add To Cart</a>
</div>
</div>
      
      </div>
      
      
      
      <!--slide 5-------------------------------------->
      <div class="swiper-slide">
      <div class="slider-box">
<p class="time">New</p>
<div class="img-box">
<img src="{% static 'images/car.jpg' %}">
</div>
<p class="detail">Black ladies bags collections
<a href="#" class="price">Price-40$</a>
</p>
<div class="cart">
<a href="#">Add To Cart</a>
</div>
</div>
      
      </div>
      
      
      
      
      <!--slide 6-------------------------------------->
      <div class="swiper-slide">
      <div class="slider-box">
<p class="time">New</p>
<div class="img-box">
<img src="{% static 'images/car.jpg' %}">
</div>
<p class="detail">Black ladies bags collections
<a href="#" class="price">Price-40$</a>
</p>
<div class="cart">
<a href="#">Add To Cart</a>
</div>
</div>
      
      </div>
      
      
      
      
      
      
      
      <!--slide 7-------------------------------------->
      <div class="swiper-slide">
      <div class="slider-box">
<p class="time">New</p>
<div class="img-box">
<img src="{% static 'images/car.jpg' %}">
</div>
<p class="detail">Black ladies bags collections
<a href="#" class="price">Price-40$</a>
</p>
<div class="cart">
<a href="#">Add To Cart</a>
</div>
</div>
      
      </div>
      
      
      
      
      <!--slide 8-------------------------------------->
      <div class="swiper-slide">
      <div class="slider-box">
<p class="time">New</p>
<div class="img-box">
<img src="{% static 'images/car.jpg' %}">
</div>
<p class="detail">Black ladies bags collections
<a href="#" class="price">Price-40$</a>
</p>
<div class="cart">
<a href="#">Add To Cart</a>
</div>
</div>
      
      </div>
    
      
</div>
</div>
<!--swiper  slider end-->
<script type="text/javascript" src="js/swiper.min.js"></script>
<script src="js/script.js"></script>
</body>
</html>

 

templates/temp/indexnav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">

    <a class="navbar-brand" href="{% url 'index' %}">DJANGO E-COMMERCE APP</a>
<!---->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{% url 'products:products' %}" id="navbarDropdown"
                    role="button" data-hover="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" onclick="Login();">
                    Products
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'products:products' %}">Parts & Accessories</a>
                    <a class="dropdown-item" href="{% url 'products:gears' %}">Riding Gears</a>
                    <!-- <div class="dropdown-divider"></div> -->
                    <a class="dropdown-item" href="{% url 'products:bikes' %}">Cars & Bikes</a>
                    <!-- <a class="dropdown-item" href="{% url 'products:products' %}">Disk brakes</a> -->
                </div>
            </li>

            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#Profile" id="navbarDropdown" role="button" data-toggle="dropdown" data-hover="dropdown" aria-haspopup="true" aria-expanded="false">
                    <!-- <i class="fa fa-user-circle" aria-hidden="tr- -->
                    Profile
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <!-- <a class="dropdown-item" href="{{request.user}}">dhg</a> -->
                    <a class="dropdown-item" href="{% url 'account:home' %}">Profile</a>
                    <a class="dropdown-item" href="{% url 'orders:list' %}">Orders</a>
                    
                  <a class="dropdown-item" href="{% url 'returnpolicy' %}">Return policy</a>
                  <!-- <a class="dropdown-item" href="#">Billing</a>
                  <a class="dropdown-item" href="#">Prefernces</a> -->
                  <!-- <a class="dropdown-item" href="#">History</a> -->
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
              </li>
            {% else %}
            <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                <a class="nav-link" href="{% url 'login'%}">Login</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
            <form class="form-inline my-2 my-lg-0 search-form" action="{% url 'search' %}"  method="GET" autocomplete="on"  required >
                <div class="wrap">
                <div class="search">
                <input class="searchTerm" type="search" name="q" placeholder="Search">
                <button class="searchButton" type="submit">
                    <i class="fa fa-search" aria-hidden="true"></i></button>
            </form>
                </div>
            </div>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'cart:cart' %}"> <span class='navbar-cart-count'>{% if not cart_id.isordered %} {{request.session.cart_items}} {% else %} {{0}} {% endif %}</span><img src="{% static 'images/cart.png' %}" alt="" /></a>
            </li>

        </ul>

    </div>
</nav>

templates/temp/policy.html
{% include "nav.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <p><br><br>
            <center><b>MM Enduro Privacy Policy</b></center><br><br>

This Privacy Policy describes how your personal information is collected, used, and shared when you visit or make a purchase from https://mmenduro.com/.<br><br>

<b>PERSONAL INFORMATION WE COLLECT</b><br>

When you visit the Site, we automatically collect certain information about your device, including information about your web browser, IP address, time zone, and some of the cookies that are installed on your device. 
Additionally, as you browse the Site, we collect information about the individual web pages or products that you view, what websites or search terms referred you to the Site, and information about how you interact with the Site. We refer to this automatically-collected information as “Device Information.”<br>

We collect Device Information using the following technologies:<br>
<ul>
    <li> “Cookies” are data files that are placed on your device or computer and often include an anonymous unique identifier. For more information about cookies, and how to disable cookies, visit http://www.allaboutcookies.org.</li>
    <li> “Log files” track actions occurring on the Site, and collect data including your IP address, browser type, Internet service provider, referring/exit pages, and date/time stamps.</li>
    <li> “Web beacons,” “tags,” and “pixels” are electronic files used to record information about how you browse the Site.</li>
    </ul>
    

Additionally when you make a purchase or attempt to make a purchase through the Site, we collect certain information from you, including your name, billing address, shipping address, payment information (including credit card numbers, email address, and phone number.  We refer to this information as “Order Information.”<br><br>

<b>PRIVACY</b><br>

When we talk about “Personal Information” in this Privacy Policy, we are talking both about Device Information and Order Information.<br>
Certain areas of this Website are restricted from being access by you and MM ENDURO may further restrict access by you to any areas of this Website, at any time, in absolute discretion. Any user ID and password you may have for this Website are confidential and you must maintain confidentiality as well.
Your Content must be your own and must not be invading any third-party’s rights. MM ENDURO reserves the right to remove any of Your Content from this Website at any time without notice.
The data store in here fully safe and secured so that other than user no one can use it <br><br>

<b>MINORS</b><br>
The Site can be used by anyone of any page .<br><br>

<b>CHANGES</b><br>
We may update this privacy policy from time to time in order to reflect, for example, changes to our practices or for other operational, legal or regulatory reasons.<br><br>

<b>CONTACT US</b><br>
For more information about our privacy practices, if you have questions, or if you would like to make a complaint, please contact us by e-mail at sanjaysan648@gmail.com or by mail using the details provided below:

  4a New Secretariat Colony , 2nd Street, Chennai, TN, 600042, India<br><br>
        </p>
    </div>
    {% include "footer.html" %}
</body>
</html>